# This YAML file defines two Kubernetes Pod objects for deploying web applications

# Define a Pod with the name "webapp" and label it as "app: webapp" and "release: 0"
apiVersion: v1                                 # Kubernetes API version
kind: Pod                                       # Kind of Kubernetes object to create Pod
metadata:                                      # Metadata for the Pod
  name: webapp                                 # Name of the Pod
  labels:                                      # Labels for the Pod
    app: webapp                                # Label for the application
    release: "0"                               # Label for the release version
spec:                                          # Specification for the Pod
  containers:                                  # Containers for the Pod
    - name: webapp                             # Name of the container
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0   # Image to use for the container

---
# Define another Pod with the name "webapp-release-0-5" and label it as "app: webapp" and "release: 0-5"
apiVersion: v1                   
kind: Pod                                      
metadata:                      
  name: webapp-release-0-5
  labels:                    
    app: webapp                     
    release: "0-5"                             # Label for the new  release version
spec:                               
  containers:                    
    - name: webapp              
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5  # New release Image to use for the container
